name: Fly Preview

on:
  pull_request:
    branches-ignore:
      - release
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - ".github/workflows/fly-preview.yml"
      - "pipeline/**"

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: fly-preview-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  review_app:
    name: Deploy PR preview pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy preview app
        uses: superfly/fly-pr-review-apps@1.6.0
        with:
          name: sorigamis-pr-${{ github.event.number }}
          path: pipeline
          config: fly.preview.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
